import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <nav className="nav" >
          <a href="/contactos" id="">contactos</a>
          <a href="/foro" id="">foro</a>
          <a href="/productos" id="">productos</a>
          <a href="http://localhost:3000">inicio</a>
        </nav>
        
        {children}

      <footer>

        <p>Created with Next.js</p>

      </footer>


      </body>
    </html>
  );
}
